[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 1
ffi = false
fs_permissions = [{ access = "read", path = "./" }]

[profile.default.fmt]
line_length = 120
tab_width = 4
bracket_spacing = false

[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
base = "${BASE_RPC_URL}"

[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}", chain = "base-sepolia" }
